"""empty message

Revision ID: 53c8acd59f7d
Revises: 38bd83c30f6c
Create Date: 2017-04-12 11:54:13.704484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c8acd59f7d'
down_revision = '38bd83c30f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('phone', sa.String(length=17), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'phone')
    # ### end Alembic commands ###
