"""empty message

Revision ID: 89428e56944f
Revises: ea2dbbd79746
Create Date: 2017-04-10 13:06:58.937733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89428e56944f'
down_revision = 'ea2dbbd79746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'contact', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'contact_id')
    # ### end Alembic commands ###
