"""empty message

Revision ID: ea2dbbd79746
Revises: 59f5361f5154
Create Date: 2017-04-10 11:54:25.525548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea2dbbd79746'
down_revision = '59f5361f5154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('registrant', sa.String(length=16), nullable=False))
    op.alter_column('contact', 'cc',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.alter_column('contact', 'city',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('contact', 'person',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index('contact_id', table_name='contact')
    op.create_unique_constraint(None, 'contact', ['registrant'])
    op.drop_column('contact', 'contact_id')
    op.drop_column('domain', 'registrant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('registrant', mysql.VARCHAR(length=16), nullable=False))
    op.add_column('contact', sa.Column('contact_id', mysql.VARCHAR(length=16), nullable=False))
    op.drop_constraint(None, 'contact', type_='unique')
    op.create_index('contact_id', 'contact', ['contact_id'], unique=True)
    op.alter_column('contact', 'person',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('contact', 'city',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('contact', 'cc',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    op.drop_column('contact', 'registrant')
    # ### end Alembic commands ###
