"""empty message

Revision ID: f0abcd90b819
Revises: 75aa327c945f
Create Date: 2017-04-09 23:20:28.034773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0abcd90b819'
down_revision = '75aa327c945f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.String(length=16), nullable=False),
    sa.Column('person', sa.String(length=255), nullable=True),
    sa.Column('org', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('cc', sa.String(length=2), nullable=True),
    sa.Column('email', sa.String(length=240), nullable=False),
    sa.Column('crDate', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id')
    )
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('registrant', sa.String(length=16), nullable=False),
    sa.Column('crDate', sa.DateTime(), nullable=True),
    sa.Column('exDate', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=240), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('fullname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=240), nullable=False),
    sa.Column('active', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    op.drop_table('domain')
    op.drop_table('contact')
    # ### end Alembic commands ###
